### ISSUE TITLE
Ordering of LayerWidget's can break popup functionality

### ISSUE THREAD

**Issue by bmason8** [rorystephenson/flutter_map_marker_popup#23] opened 2021-06-11 16:32 UTC
I've noticed that if you put a _PolylineLayerWidget_ or _PolygonLayerWidget_ AFTER a _PopupMarkerLayerWidget_ it breaks the popup functionality of the popup marker. Layers will still show correctly but nothing happens when you click on a marker and no error/exception is thrown so you don't know you're doing something wrong. 

Sorry if this is in the documentation somewhere and it's known behaviour but I suspect it's not so I'm mentioning it.

**Comment by rorystephenson** [comment] 2021-06-12 14:13
> I've noticed that if you put a _PolylineLayerWidget_ or _PolygonLayerWidget_ AFTER a _PopupMarkerLayerWidget_ it breaks the popup functionality of the popup marker. Layers will still show correctly but nothing happens when you click on a marker and no error/exception is thrown so you don't know you're doing something wrong.
> 
> Sorry if this is in the documentation somewhere and it's known behaviour but I suspect it's not so I'm mentioning it.

Hmm interesting I have to admit I haven't tried! If it's causing you problems and you'd like to share a minimal example I'm happy to have a look.

**Comment by rorystephenson** [comment] 2021-06-21 08:46
@bmason8 I'm going to close this for now but if you or someone else continue to have issues and can provide a minimal example I'll be happy to check it out!

**Comment by Swepilot** [comment] 2021-10-31 11:08
@rorystephenson 
I too am experiencing this now. I have been using this repo for over a year and had many both MarkerLayerOptions together with other types of layers as both LayerOptions and Widgets in FlutterMap. Never had any issues as long as I ordered them logically.

However, now having to update various components due to the LatLong/LatLong2 issue I am having serious issues with the popups in version 2.0.0. Basically, if I add anything to a nonRotatedLayer the popup functionality stops working. Let's say I add lat_long_grid_plugin in a nonRotatedLayer, then popups stop working. It doesn't matter if I place the nonRotatedLayer before or after nonRotatedChildren, as layers are always rendered on top of the widgets.

**Comment by Swepilot** [comment] 2021-10-31 12:45
Working example

```
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_map_marker_popup/flutter_map_marker_popup.dart';
import 'package:latlong2/latlong.dart';
import 'package:lat_lon_grid_plugin/lat_lon_grid_plugin.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Map Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Map Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(

          title: Text(widget.title),
        ),
        body: Center(
          child: Container(
            height: MediaQuery.of(context).size.height,
            child: FlutterMap(
              options: MapOptions(
                center: LatLng(0, 0),
                plugins: [
                  MapPluginLatLonGrid(),
                ],
              ),
              nonRotatedLayers: [
                // Comment/uncomment MapPluginLatLongGridOption below to hide/show 
                // the latlong grids and notice how popup of the marker is 
                //not working the the grids showing
                
                // MapPluginLatLonGridOptions(
                //   lineColor: Colors.grey,
                //   textColor: Colors.white,
                //   lineWidth: 1,
                //   textBackgroundColor: Colors.grey,
                //   showCardinalDirections: true,
                //   showCardinalDirectionsAsPrefix: true,
                //   textSize: 12.0,
                //   showLabels: true,
                //   rotateLonLabels: true,
                //   placeLabelsOnLines: true,
                //   offsetLonTextBottom: 20.0,
                //   offsetLatTextLeft: 20.0,
                // ),
              ],
              nonRotatedChildren: [
                PopupMarkerLayerWidget(
                    options: PopupMarkerLayerOptions(
                        popupBuilder: (BuildContext context, Marker marker) {
                          return Text("Test popupmarker");
                        },
                        markers: [
                      Marker(
                          point: LatLng(0, 0),
                          builder: (BuildContext context) {
                            return Icon(Icons.location_on);
                          })
                    ]))
              ],
            ),
          ),
        ));
  }
}

```

**Comment by rorystephenson** [comment] 2021-10-31 17:38
Thanks for the example code @Swepilot, I've had a look and this is caused by the fact that flutter_map doesn't allow you to put children/non-rotated children on top of layers and the lat lon grid plugin doesn't support being added as a widget. I'm going to close this here and comment on the issue you opened in the flutter_map repository since I think it belongs there.

**Closed by rorystephenson** 2021-10-31 17:38 UTC
